service: tabler-world-api

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-aws-alerts
  - serverless-domain-manager
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

  webpack:
    keepOutputDirectory: true
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk

  cache_table:
    Fn::ImportValue: CacheTableName-${self:custom.stage}

  email: ${env:ALERT_EMAIL}

  domainname: ${self:custom.stage}-api.app.roundtable.world
  wsdomainname: ${self:custom.stage}-ws-api.app.roundtable.world

  demo_api_key: ${env:DEMO_API_KEY}

  connections_table: tabler-world-ws-connections-${self:custom.stage}
  subscriptions_table: tabler-world-ws-subscriptions-${self:custom.stage}
  conversations_table: tabler-world-chat-conversations-${self:custom.stage}
  pushsubscriptions_table: tabler-world-push-subscriptions-${self:custom.stage}
  events_table: tabler-world-ws-events-${self:custom.stage}

  # api throtteling
  throttle:
    dev:
      burstLimit: 10
      rateLimit: 5

    test:
      burstLimit: 40
      rateLimit: 20

    prod:
      burstLimit: 200
      rateLimit: 100

  bundle:
    dev: false
    test: true
    prod: true

  # SNS topics to check env
  alerts:
    stages:
      - test
      - prod

    topics:
      alarm:
        topic: ${self:service}-${self:custom.stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${self:custom.email}

    alarms:
      - functionErrors
      - processTimeouts

    definitions:
      processTimeouts:
        metric: processTimeouts
        threshold: 0
        statistic: Minimum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        pattern: 'Process exited before completing'

  # domain
  customDomain:
    domainName: ${self:custom.domainname}
    certificateName: '*.app.roundtable.world'
    createRoute53Record: true
    endpointType: 'regional'
    websockets:
      domainName: ${self:custom.wsdomainname}
      certificateName: '*.app.roundtable.world'
      createRoute53Record: true
      endpointType: 'regional'
      stage: '${self:custom.stage}'

  # chat
  dynamodb:
    noStart: false
    stages:
      - dev
    start:
      port: 8004
      inMemory: true
      migrate: true
      convertEmptyValues: true

# we want seperate files to minimize depenencies in files
package:
  individually: ${self:custom.bundle.${self:custom.stage}}

provider:
  name: aws
  stage: dev
  region: eu-west-1

  runtime: nodejs10.x

  memorySize: 128
  versionFunctions: false

  tracing:
    apiGateway: true

  # allow to redefine variables for debug purposes
  environment:
    ${file(serverless.env.yml):${self:custom.stage}}

  apiKeys:
    - app:
      - name: tabler-world-api-lambda-authorizer-${self:custom.stage}
        # this is hardcoded also in code, move?
        value: tabler-world-api-lambda-authorizer-${self:custom.stage}

    - demo:
      - name: tabler-world-demo-${self:custom.stage}
        value: ${self:custom.demo_api_key}

  apiGateway:
    minimumCompressionSize: 1024
    apiKeySourceType: AUTHORIZER
#    websocketsApiKeySelectionExpression: "$context.authorizer.usageIdentifierKey"

  # Limited by API Keys
  usagePlan:
    - app:
        throttle:
          burstLimit: ${self:custom.throttle.${self:custom.stage}.burstLimit}
          rateLimit: ${self:custom.throttle.${self:custom.stage}.rateLimit}

    - demo:
        throttle:
          burstLimit: ${self:custom.throttle.${self:custom.stage}.burstLimit}
          rateLimit: ${self:custom.throttle.${self:custom.stage}.rateLimit}

  # global role definition
  iamRoleStatements:
    # allow database access
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        Fn::ImportValue: DataArn-${self:custom.stage}

    # read parameters from SSM
    - Effect: Allow
      Action:
        - ssm:GetParameters
        - ssm:GetParameter
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:ssm:"
            - ${self:provider.region}
            - ":"
            - Ref: "AWS::AccountId"
            - ":parameter*/"
            - ${self:custom.stage}
            - "/*"

    # tracing AWSXrayWriteOnlyAccess
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
        - xray:GetSamplingRules
        - xray:GetSamplingTargets
        - xray:GetSamplingStatisticSummaries

      Resource:
        - "*"

functions:
  #
  # Update database
  #
  database-update:
    handler: src/sql/lambda.handler
    timeout: 600

    environment:
      db_role: tw_read_${self:custom.stage}
      XRAY_DISABLED: true

  #
  # graphql Demo
  #
  graphql-demo:
    handler: src/graphql/graphqlLambdaMock.handler
    timeout: 15
    memorySize: 128
    tracing: Active

    events:
        - http:
            path: graphql-demo
            method: post
            authorizer:
              type: CUSTOM
              authorizerId:
                Ref: CustomApiGatewayAuthorizer
            cors: true
            private: true

  #
  # graphql
  #
  graphql:
    handler: src/graphql/graphqlLambda.handler
    timeout: 30
    memorySize: 256
    tracing: Active

    environment:
      ${file(serverless.env.yml):api}

    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem

        # Restrict our IAM role permissions to
        # the specific table for the stage
        Resource:
          - Fn::ImportValue: CacheTableArn-${self:custom.stage}
          - !GetAtt [ connectionsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ connectionsTable, Arn ]
              - '/index/*'
          - !GetAtt [ subscriptionsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ subscriptionsTable, Arn ]
              - '/index/*'
          - !Join
            - ''
            - - !GetAtt [ subscriptionsTable, Arn ]
              - '/index/connection'
          - !GetAtt [ conversationsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ conversationsTable, Arn ]
              - '/index/*'
          - !GetAtt [ eventsTable, Arn ]
          - !GetAtt [ pushSubscriptionsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ pushSubscriptionsTable, Arn ]
              - '/index/*'

      - Effect: Allow
        Action:
          - 'execute-api:Invoke'
          - 'execute-api:ManageConnections'
        Resource: !Join
          - ''
          - - 'arn:aws:execute-api:${self:provider.region}:'
            - !Ref 'AWS::AccountId'
            - ':'
            - !Ref WebsocketsApi
            - '/${self:provider.stage}/*'

    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId:
              Ref: CustomApiGatewayAuthorizer
          private: true

      - http:
          path: graphql
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId:
              Ref: CustomApiGatewayAuthorizer
          private: true

  #
  # websocket
  #
  websocket:
    handler: src/graphql/websocketLambda.handler
    tracing: Active
    environment:
      ${file(serverless.env.yml):api}

    events:
      - websocket:
          route: $connect
          cors: true

      - websocket:
         route: $disconnect

      - websocket:
         route: $default

    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'execute-api:Invoke'
          - 'execute-api:ManageConnections'
        Resource: !Join
          - ''
          - - 'arn:aws:execute-api:${self:provider.region}:'
            - !Ref 'AWS::AccountId'
            - ':'
            - !Ref WebsocketsApi
            - '/${self:provider.stage}/*'

      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem

        # Restrict our IAM role permissions to
        # the specific table for the stage
        Resource:
          - Fn::ImportValue: CacheTableArn-${self:custom.stage}
          - !GetAtt [ connectionsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ connectionsTable, Arn ]
              - '/index/*'
          - !GetAtt [ subscriptionsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ subscriptionsTable, Arn ]
              - '/index/*'
          - !Join
            - ''
            - - !GetAtt [ subscriptionsTable, Arn ]
              - '/index/connection'
          - !GetAtt [ conversationsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ conversationsTable, Arn ]
              - '/index/*'
          - !GetAtt [ eventsTable, Arn ]
          - !GetAtt [ pushSubscriptionsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ pushSubscriptionsTable, Arn ]
              - '/index/*'

  #
  # publish messagees
  #
  publish:
    handler: src/graphql/publishMessageLambda.handler
    tracing: Active
    environment:
      ${file(serverless.env.yml):api}

    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn: !GetAtt
            - eventsTable
            - StreamArn

    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem

        # Restrict our IAM role permissions to
        # the specific table for the stage
        Resource:
          - Fn::ImportValue: CacheTableArn-${self:custom.stage}
          - !GetAtt [ connectionsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ connectionsTable, Arn ]
              - '/index/*'
          - !GetAtt [ subscriptionsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ subscriptionsTable, Arn ]
              - '/index/*'
          - !Join
            - ''
            - - !GetAtt [ subscriptionsTable, Arn ]
              - '/index/*'
          - !GetAtt [ conversationsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ conversationsTable, Arn ]
              - '/index/*'
          - !GetAtt [ eventsTable, Arn ]
          - !GetAtt [ pushSubscriptionsTable, Arn ]
          - !Join
            - ''
            - - !GetAtt [ pushSubscriptionsTable, Arn ]
              - '/index/*'

      - Effect: Allow
        Action:
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
        Resource: !GetAtt [ eventsTable, StreamArn ]

      - Effect: Allow
        Action:
          - 'execute-api:Invoke'
          - 'execute-api:ManageConnections'
        Resource: !Join
          - ''
          - - 'arn:aws:execute-api:${self:provider.region}:'
            - !Ref 'AWS::AccountId'
            - ':'
            - !Ref WebsocketsApi
            - '/${self:provider.stage}/*'

      - Effect: Allow
        Action:
          - sqs:SendMessage
          - sqs:SendMessageBatch
        Resource:
          Fn::ImportValue: PushQueueArn-${self:custom.stage}

resources:
  Resources:
    connectionsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.connections_table}

        AttributeDefinitions:
          - AttributeName: memberId
            AttributeType: N
          - AttributeName: connectionId
            AttributeType: S

        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH

        GlobalSecondaryIndexes:
          - IndexName: reverse
            KeySchema:
              - AttributeName: memberId
                KeyType: HASH
              - AttributeName: connectionId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    subscriptionsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.subscriptions_table}

        AttributeDefinitions:
          - AttributeName: eventName
            AttributeType: S
          - AttributeName: subscription
            AttributeType: S
          - AttributeName: connectionId
            AttributeType: S

        KeySchema:
          - AttributeName: subscription
            KeyType: HASH

        GlobalSecondaryIndexes:
          - IndexName: connection
            KeySchema:
              - AttributeName: connectionId
                KeyType: HASH
              - AttributeName: subscription
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY

          - IndexName: reverse
            KeySchema:
              - AttributeName: eventName
                KeyType: HASH
              - AttributeName: subscription
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    pushSubscriptionsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.pushsubscriptions_table}

        AttributeDefinitions:
          - AttributeName: conversation
            AttributeType: S
          - AttributeName: memberId
            AttributeType: N
        KeySchema:
          - AttributeName: conversation
            KeyType: HASH
          - AttributeName: memberId
            KeyType: RANGE

        GlobalSecondaryIndexes:
          - IndexName: reverse
            KeySchema:
              - AttributeName: memberId
                KeyType: HASH
              - AttributeName: conversation
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY

    conversationsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.conversations_table}

        AttributeDefinitions:
          - AttributeName: conversation
            AttributeType: S
          - AttributeName: memberId
            AttributeType: N
          - AttributeName: last_conversation
            AttributeType: S

        KeySchema:
          - AttributeName: conversation
            KeyType: HASH
          - AttributeName: memberId
            KeyType: RANGE

        GlobalSecondaryIndexes:
          # - IndexName: reverse
          #   KeySchema:
          #     - AttributeName: memberId
          #       KeyType: HASH
          #     - AttributeName: conversation
          #       KeyType: RANGE
          #   Projection:
          #     ProjectionType: KEYS_ONLY

          - IndexName: last_conversation
            KeySchema:
              - AttributeName: memberId
                KeyType: HASH
              - AttributeName: last_conversation
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY


    eventsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.events_table}
        AttributeDefinitions:
          - AttributeName: eventName
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: eventName
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_IMAGE

        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    GraphqlDashdemoLogGroup:
      Properties:
        RetentionInDays: "7"

    GraphqlLogGroup:
      Properties:
        RetentionInDays: "14"

    DatabaseDashupdateLogGroup:
      Properties:
        RetentionInDays: "7"

    LambdaPermissionAuthorizerApiGateway:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::ImportValue: AuthorizerArn-${self:custom.stage}
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com

    # https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html
    CustomApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: lambda-${self:custom.stage}
        IdentitySource: method.request.header.Authorization
        AuthorizerResultTtlInSeconds: 3600
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: TOKEN
        AuthorizerUri:
         Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::ImportValue: AuthorizerArn-${self:custom.stage}
            - "/invocations"

  Outputs:
    ApiUrl:
      Value: ${self:custom.domainname}
      Export:
        Name: ApiUrl-${self:custom.stage}

    WSApiUrl:
      Value: ${self:custom.wsdomainname}
      Export:
        Name: ApiWSUrl-${self:custom.stage}

    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ApiGatewayRestApiId-${self:custom.stage}

    ApiGatewayRestApiRootResourceId:
      Value:
         !GetAtt
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ApiGatewayRestApiRootResourceId-${self:custom.stage}

    ApiArn:
      Value:
        !GetAtt
          # functions are renamed acording to https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/resources.md
          - GraphqlLambdaFunction
          - Arn
      Export:
        Name: ApiArn-${self:custom.stage}
