service: tabler-world-api

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-aws-alerts
  - serverless-domain-manager
  - serverless-offline
  - serverless-webpack

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

  webpack:
    keepOutputDirectory: true
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk

  cache_table:
    Fn::ImportValue: CacheTableName-${self:custom.stage}

  email: ${env:ALERT_EMAIL}

  domainname: ${self:custom.stage}-api.app.roundtable.world
  demo_api_key: ${env:DEMO_API_KEY}

  # api throtteling
  throttle:
    dev:
      burstLimit: 10
      rateLimit: 5

    test:
      burstLimit: 40
      rateLimit: 20

    prod:
      burstLimit: 200
      rateLimit: 100

  bundle:
    dev: false
    test: true
    prod: true

  # SNS topics to check env
  alerts:
    stages:
      - test
      - prod

    topics:
      alarm:
        topic: ${self:service}-${self:custom.stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${self:custom.email}

    alarms:
      - functionErrors
      - processTimeouts

    definitions:
      processTimeouts:
        metric: processTimeouts
        threshold: 0
        statistic: Minimum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        pattern: 'Process exited before completing'

  # domain
  customDomain:
    domainName: ${self:custom.domainname}
    certificateName: '*.app.roundtable.world'
    createRoute53Record: true
    endpointType: 'regional'

# we want seperate files to minimize depenencies in files
package:
  individually: ${self:custom.bundle.${self:custom.stage}}

provider:
  name: aws
  stage: dev
  region: eu-west-1

  runtime: nodejs10.x

  memorySize: 128
  versionFunctions: false

  tracing:
    apiGateway: true

  # allow to redefine variables for debug purposes
  environment:
    ${file(serverless.env.yml):${self:custom.stage}}

  apiKeys:
    - app:
      - name: tabler-world-api-lambda-authorizer-${self:custom.stage}
        # this is hardcoded also in code, move?
        value: tabler-world-api-lambda-authorizer-${self:custom.stage}

    - demo:
      - name: tabler-world-demo-${self:custom.stage}
        value: ${self:custom.demo_api_key}

  apiGateway:
    minimumCompressionSize: 1024
    apiKeySourceType: AUTHORIZER

  # Limited by API Keys
  usagePlan:
    - app:
        throttle:
          burstLimit: ${self:custom.throttle.${self:custom.stage}.burstLimit}
          rateLimit: ${self:custom.throttle.${self:custom.stage}.rateLimit}

    - demo:
        throttle:
          burstLimit: ${self:custom.throttle.${self:custom.stage}.burstLimit}
          rateLimit: ${self:custom.throttle.${self:custom.stage}.rateLimit}

  # global role definition
  iamRoleStatements:
    # allow database access
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        Fn::ImportValue: DataArn-${self:custom.stage}

    # read parameters from SSM
    - Effect: Allow
      Action:
        - ssm:GetParameters
        - ssm:GetParameter
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:ssm:"
            - ${self:provider.region}
            - ":"
            - Ref: "AWS::AccountId"
            - ":parameter*/"
            - ${self:custom.stage}
            - "/*"

    # tracing AWSXrayWriteOnlyAccess
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
        - xray:GetSamplingRules
        - xray:GetSamplingTargets
        - xray:GetSamplingStatisticSummaries

      Resource:
        - "*"

functions:
  #
  # Update database
  #
  database-update:
    handler: src/sql/lambda.handler
    timeout: 600

    environment:
      db_role: tw_read_${self:custom.stage}
      XRAY_DISABLED: true

  #
  # graphql Demo
  #
  graphql-demo:
    handler: src/graphql/lambda-mock.handler
    timeout: 15
    memorySize: 128
    tracing: Active

    events:
        - http:
            path: graphql-demo
            method: post
            authorizer:
              type: CUSTOM
              authorizerId:
                Ref: CustomApiGatewayAuthorizer
            cors: true
            private: true

  #
  # graphql
  #
  graphql:
    handler: src/graphql/lambda.handler
    timeout: 30
    memorySize: 256
    tracing: Active

    environment:
      cache_table: ${self:custom.cache_table}

    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem

        # Restrict our IAM role permissions to
        # the specific table for the stage
        Resource:
          - Fn::ImportValue: CacheTableArn-${self:custom.stage}

    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId:
              Ref: CustomApiGatewayAuthorizer
          private: true

      - http:
          path: graphql
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId:
              Ref: CustomApiGatewayAuthorizer
          private: true


resources:
  Resources:
    GraphqlDashdemoLogGroup:
      Properties:
        RetentionInDays: "7"

    GraphqlLogGroup:
      Properties:
        RetentionInDays: "14"

    DatabaseDashupdateLogGroup:
      Properties:
        RetentionInDays: "7"

    LambdaPermissionAuthorizerApiGateway:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::ImportValue: AuthorizerArn-${self:custom.stage}
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com

    # https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html
    CustomApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: lambda-${self:custom.stage}
        IdentitySource: method.request.header.Authorization
        AuthorizerResultTtlInSeconds: 3600
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: TOKEN
        AuthorizerUri:
         Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::ImportValue: AuthorizerArn-${self:custom.stage}
            - "/invocations"

  Outputs:
    ApiUrl:
      Value: ${self:custom.domainname}
      Export:
        Name: ApiUrl-${self:custom.stage}

    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ApiGatewayRestApiId-${self:custom.stage}

    ApiGatewayRestApiRootResourceId:
      Value:
         Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ApiGatewayRestApiRootResourceId-${self:custom.stage}

    ApiArn:
      Value:
        Fn::GetAtt:
          # functions are renamed acording to https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/resources.md
          - GraphqlLambdaFunction
          - Arn
      Export:
        Name: ApiArn-${self:custom.stage}
