# build number
name: $(VERSION).$(rev:r)

pool:
  name: Default # Hosted Ubuntu 1604
  demands: npm yarn

variables:
  - name: VERSION
    value: 1.1
  - name: EXPO_RELEASE_CHANNEL
    value: beta

steps:
- script: 'echo "$(Build.SourceVersionMessage)" > commit.txt'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

# yarn /
- template: ./devops/yarn.yml
  parameters:
    SOURCEDIR: $(System.DefaultWorkingDirectory)

# yarn /App
- template: ./devops/yarn.yml
  parameters:
    SOURCEDIR: $(System.DefaultWorkingDirectory)/App

# yarn /App
- template: ./devops/yarn.yml
  parameters:
    SOURCEDIR: $(System.DefaultWorkingDirectory)/App

# yarn /App
- template: ./devops/init-expo.yml
  parameters:
    APPDIR: $(System.DefaultWorkingDirectory)/App
    APP_VERSION: $(build.buildNumber)
    SOURCESDIR: $(System.DefaultWorkingDirectory)

- script: |
   export CHANNEL="$(build.buildNumber)-$(EXPO_RELEASE_CHANNEL)"
   npx expo publish --non-interactive --max-workers 1 --release-channel $CHANNEL
   npx expo publish:history --release-channel $CHANNEL -r > deployment.json
  workingDirectory: '$(System.DefaultWorkingDirectory)/App'
  displayName: publish
  env:
    SENTRY_AUTH_TOKEN: $(SENTRY_AUTH_TOKEN)

# yarn /App
- template: ./devops/publish.yml
