# build number
name: $(VERSION).$(PATCH)

pool:
  name: 'Default' # 'Hosted Ubuntu 1604
  demands: npm

variables:
  - name: VERSION
    value: '1.1'
  - name: PATCH
    value: $[counter(variables['VERSION'], 47)]
  - name: EXPO_RELEASE_CHANNEL
    value: 'beta'
  - group: 'expo'
  - group: 'git-crypt'
  - group: 'ENV Germany Shared'
  - group: 'ENV Germany TEST'

steps:
- script: 'echo "$(Build.SourceVersionMessage)" > commit.txt'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- template: ./devops/node.yml

# yarn /
- template: ./devops/yarn.yml
  parameters:
    SOURCEDIR: $(System.DefaultWorkingDirectory)

# yarn /App
- template: ./devops/yarn.yml
  parameters:
    SOURCEDIR: $(System.DefaultWorkingDirectory)/App

# yarn /App
- template: ./devops/init-expo.yml
  parameters:
    APPDIR: $(System.DefaultWorkingDirectory)/App
    APP_VERSION: $(build.buildNumber)
    SOURCESDIR: $(System.DefaultWorkingDirectory)

- script: |
   export CHANNEL="$(build.buildNumber)-$(EXPO_RELEASE_CHANNEL)"
   npx expo publish --non-interactive --max-workers 1 --release-channel $CHANNEL
   npx expo publish:history --release-channel $CHANNEL -r > deployment.json
  workingDirectory: '$(System.DefaultWorkingDirectory)/App'
  displayName: publish
  env:
    SENTRY_AUTH_TOKEN: $(SENTRY_AUTH_TOKEN)

# yarn /App
- template: ./devops/publish.yml
