parameters:
  ARTIFACT: 'app-config'
  PATH: 'apps/tabler-app'

steps:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: commit.txt
    ArtifactName: ${{ parameters.ARTIFACT }}

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: ${{ parameters.PATH }}/app.json
    ArtifactName: ${{ parameters.ARTIFACT }}

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: apps/tabler-app/package.json
#     ArtifactName: ${{ parameters.ARTIFACT }}

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: .yarnrc
    ArtifactName: ${{ parameters.ARTIFACT }}

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: yarn.lock
#     ArtifactName: ${{ parameters.ARTIFACT }}

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: App/yarn.lock
#     ArtifactName: ${{ parameters.ARTIFACT }}

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: ${{ parameters.PATH }}/deployment.json
    ArtifactName: ${{ parameters.ARTIFACT }}

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: ${{ parameters.PATH }}/devops/deployment.js
    ArtifactName: ${{ parameters.ARTIFACT }}/config

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: ${{ parameters.PATH }}/devops/setvar.ps1
    ArtifactName: ${{ parameters.ARTIFACT }}/config

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: apps/tabler-app/assets
#     ArtifactName: ${{ parameters.ARTIFACT }}/assets

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: packages
#     ArtifactName: packages
