service: tabler-world-chat

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    PUBLISH_ENDPOINT: !Join
        - ''
        - - 'https://'
          - !Ref WebsocketsApi
          - '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/'
    CONNECTIONS_TABLE: 'CHAT_CONNECTIONS'
    CHANNELS_TABLE: 'CHAT_CHANNELS'
    EVENTS_TABLE: 'CHAT_EVENTS'

package:
  individually: true

custom:
  webpack:
    keepOutputDirectory: true
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk

  serverless-offline:
    port: 4000
    websocketPort: 4001

  dynamodb:
    noStart: false
    stages:
      - dev
    start:
      port: 8004
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      convertEmptyValues: true

functions:
  graphql:
    handler: src/graphql.handler
    role: role
    events:
      - http:
          path: graphql
          method: POST
          cors:
            origin: '*'
          aauthorizer: arn:aws:lambda:us-east-1:1234567890:function:auth
          private: true

      - http:
          path: graphql
          method: get
          cors:
            origin: '*'
          authorizer: arn:aws:lambda:us-east-1:1234567890:function:auth
          private: true

  websocket:
    handler: src/websocket.handler
    role: role
    events:
      - websocket:
          route: $connect
          authorizer: arn:aws:lambda:us-east-1:1234567890:function:auth

      - websocket:
         route: $disconnect
      - websocket:
         route: $default

  publish:
    handler: src/publish.handler
    role: role
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn: !GetAtt
            - subscriptionEventsTable
            - StreamArn

resources:
  Resources:
    connectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.CONNECTIONS_TABLE}

        AttributeDefinitions:
          - AttributeName: memberId
            AttributeType: N
          - AttributeName: connectionId
            AttributeType: S

        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH

        GlobalSecondaryIndexes:
          - IndexName: reverse
            KeySchema:
              - AttributeName: memberId
                KeyType: HASH
              - AttributeName: connectionId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    channelsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.CHANNELS_TABLE}

        AttributeDefinitions:
          - AttributeName: channel
            AttributeType: S
          - AttributeName: memberId
            AttributeType: N
        KeySchema:
          - AttributeName: channel
            KeyType: HASH
          - AttributeName: memberId
            KeyType: RANGE

        GlobalSecondaryIndexes:
          - IndexName: reverse
            KeySchema:
              - AttributeName: memberId
                KeyType: HASH
              - AttributeName: channel
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    subscriptionEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.EVENTS_TABLE}
        AttributeDefinitions:
          - AttributeName: channel
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: channel
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_IMAGE

        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    role:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: ${self:service}-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: 'sts:AssumeRole'

        Policies:
          - PolicyName: logLambda
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogGroup'
                    - 'logs:CreateLogStream'
                    - 'logs:PutLogEvents'
                  Resource: !Join
                    - ''
                    - - 'arn:aws:logs:${self:provider.region}:'
                      - !Ref 'AWS::AccountId'
                      - ':log-group:/aws/lambda/*:*:*'

          - PolicyName: useDynamoDb
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'dynamodb:GetItem'
                    - 'dynamodb:PutItem'
                    - 'dynamodb:BatchWriteItem'
                    - 'dynamodb:Query'
                  Resource:
                    - !GetAtt subscriptionEventsTable.Arn

                    - !GetAtt connectionsTable.Arn
                    - !Join
                      - ''
                      - - !GetAtt connectionsTable.Arn
                        - '/index/reverse'

                    - !GetAtt channelsTable.Arn
                    - !Join
                      - ''
                      - - !GetAtt channelsTable.Arn
                        - '/index/reverse'

          - PolicyName: accessDDBStream
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:DescribeStream
                      - dynamodb:GetRecords
                      - dynamodb:GetShardIterator
                      - dynamodb:ListStreams
                    Resource: !GetAtt subscriptionEventsTable.StreamArn

          - PolicyName: publishToConnectedClients
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'execute-api:Invoke'
                    - 'execute-api:ManageConnections'
                  Resource: !Join
                    - ''
                    - - 'arn:aws:execute-api:${self:provider.region}:'
                      - !Ref 'AWS::AccountId'
                      - ':'
                      - !Ref WebsocketsApi
                      - '/${self:provider.stage}/*'


