# build number
name: $(VERSION).$(rev:r)

pool:
  name: Hosted Ubuntu 1604
  demands: npm

variables:
  VERSION: 1.1
  PACKAGE_DIR: 'services/tabler-world-auth'

trigger:
  paths:
    include:
      - packages/**/src/*
      - services/tabler-world-auth/src/*
      - services/tabler-world-auth/azure-pipelines.yml

steps:
# - template: ../devops/yarn.yml

- task: Npm@1
  inputs:
    command: custom
    workingDir: '$(PACKAGE_DIR)'
    verbose: false
    customCommand: 'version $(Build.BuildNumber)'

- template: ../devops/publish-defaults.yml

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(PACKAGE_DIR)'
    ArtifactName: source/Authentication

- powershell: |
    Write-Host "Tagging Build: $env:BuildNumber"

    git tag $env:BuildNumber
    git push origin $env:BuildNumber
  env:
    BuildNumber: tag-$(Build.BuildNumber)