# build number
name: $(VERSION).$(rev:r)

parameters:
  AWS_DEFAULT_REGION: ''
  INFRASTRUCTURE_RELEASE_CHANNEL: ''

variables:
  SOURCE: source/Authentication

jobs:
  - job: TEST

    pool:
      name: Hosted Ubuntu 1604
      demands: npm

    variables:
      - group: "AWS Germany"
      - group: "ENV Germany Shared"
      - group: "ENV Germany TEST"

    steps:
    - template: ../devops/serverless.yml
      parameters:
        SOURCEDIR: '$(System.DefaultWorkingDirectory)/source/Authentication'
        STAGE: $(INFRASTRUCTURE_RELEASE_CHANNEL)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
